#! /bin/sh

if [ -f /flag.sh ];then
    source /flag.sh
fi

if [ -f /app/requirements.txt ];then
    pip install /app/requirements.txt && rm -f /app/requirements.txt
fi

echo "Running..."

gunicorn --chdir="/app" -w 2 -b 0.0.0.0:80 -u nobody -g nogroup --access-logfile - $(MODULE_NAME):$(VARIABLE_NAME)
